server {
    listen 18081;
    server_name _;
    server_tokens off;

    add_header X-Content-Type-Options nosniff always;
    add_header Referrer-Policy strict-origin-when-cross-origin always;
    add_header X-Frame-Options SAMEORIGIN always;

    location = /pull-it {
        return 308 /pull-it/;
    }

    location /pull-it/ {
        rewrite ^/pull-it/(.*)$ /$1 break;
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }

    location = /healthz {
        add_header Content-Type text/plain;
        return 200 'ok';
    }

    location / {
        return 404;
    }
}
